import { activityTable, SaveActivityReq } from "@ddanjit/domain";
import { db } from "../mysql";

export const seedActivities = async () => {
  const activities: SaveActivityReq[] = [
    {
      title: "1분 명상하기",
      bundleId: 1,
      instruction: "눈을 감고 깊게 숨을 들이마시고 내뱉으세요. 자신의 호흡에 집중합니다.",
      icon: "sound",
      duration: "1",
      content: { type: "meditation", guide: "호흡에 집중하세요" },
      isFree: true,
      recommendAt: 9,
    },
    {
      title: "스트레칭 5분",
      bundleId: 1,
      instruction: "목, 어깨, 허리를 가볍게 스트레칭하여 긴장을 풀어주세요.",
      icon: "vision",
      duration: "5",
      content: { type: "exercise", steps: ["목 돌리기", "어깨 으쓱하기"] },
      isFree: true,
      recommendAt: 10,
    },
    {
      title: "독서 10분",
      bundleId: 1,
      instruction: "좋아하는 책의 한 페이지를 읽어보세요.",
      icon: "book",
      duration: "10",
      content: { type: "reading", pages: 2 },
      isFree: false,
      recommendAt: 14,
    },
    {
      title: "물 한 잔 마시기",
      bundleId: 1,
      instruction: "시원한 물 한 잔으로 몸을 깨우세요.",
      icon: "lightbulb",
      duration: "1",
      content: { type: "health", amount: "250ml" },
      isFree: true,
      recommendAt: 8,
    },
    {
      title: "음악 감상 15분",
      bundleId: 2,
      instruction: "차분한 클래식이나 자연의 소리를 들어보세요.",
      icon: "sound",
      duration: "15",
      content: { type: "audio", playlist: "relaxing_jazz" },
      isFree: false,
      recommendAt: 20,
    },
    {
      title: "일기 쓰기 10분",
      bundleId: 1,
      instruction: "오늘 하루의 감사한 점 3가지를 적어보세요.",
      icon: "book",
      duration: "10",
      content: { type: "writing", prompt: "gratitude" },
      isFree: true,
      recommendAt: 22,
    },
    {
      title: "간단한 정리정돈",
      bundleId: 1,
      instruction: "책상 위나 가방 안을 5분 동안 정리해보세요.",
      icon: "vision",
      duration: "5",
      content: { type: "action", target: "desk" },
      isFree: true,
      recommendAt: 13,
    },
    {
      title: "산책 20분",
      bundleId: 2,
      instruction: "가벼운 옷차림으로 주변을 산책하며 햇볕을 쬐세요.",
      icon: "vision",
      duration: "20",
      content: { type: "exercise", steps: 2000 },
      isFree: false,
      recommendAt: 16,
    },
    {
      title: "스쿼트 20회",
      bundleId: 1,
      instruction: "올바른 자세로 스쿼트를 하며 하체 근력을 키우세요.",
      icon: "electronic",
      duration: "5",
      content: { type: "exercise", count: 20 },
      isFree: true,
      recommendAt: 11,
    },
    {
      title: "심호흡 10번",
      bundleId: 1,
      instruction: "천천히 코로 들이마시고 입으로 내뱉는 심호흡을 반복하세요.",
      icon: "sound",
      duration: "1",
      content: { type: "breathing", count: 10 },
      isFree: true,
      recommendAt: 9,
    },
    {
      title: "창밖 바라보기 5분",
      bundleId: 1,
      instruction: "전자기기에서 눈을 떼고 먼 곳을 바라보며 눈의 피로를 푸세요.",
      icon: "vision",
      duration: "5",
      content: { type: "relax", target: "distance" },
      isFree: true,
      recommendAt: 15,
    },
    {
      title: "팟캐스트 듣기 30분",
      bundleId: 2,
      instruction: "관심 있는 주제의 팟캐스트를 들어보세요.",
      icon: "sound",
      duration: "30",
      content: { type: "audio", category: "tech" },
      isFree: false,
      recommendAt: 19,
    },
    {
      title: "손 씻기",
      bundleId: 1,
      instruction: "비누를 사용하여 구석구석 깨끗하게 손을 씻으세요.",
      icon: "lightbulb",
      duration: "1",
      content: { type: "hygiene", steps: "30s" },
      isFree: true,
      recommendAt: 12,
    },
    {
      title: "그림 그리기 20분",
      bundleId: 2,
      instruction: "자유로운 주제로 간단한 스케치를 해보세요.",
      icon: "vision",
      duration: "20",
      content: { type: "art", tool: "pencil" },
      isFree: false,
      recommendAt: 21,
    },
    {
      title: "새로운 단어 공부",
      bundleId: 1,
      instruction: "사전에서 새로운 단어 하나를 찾아 뜻을 익혀보세요.",
      icon: "book",
      duration: "5",
      content: { type: "study", count: 1 },
      isFree: true,
      recommendAt: 10,
    },
    {
      title: "플랭크 1분",
      bundleId: 1,
      instruction: "코어 근육을 위해 플랭크 자세를 유지해보세요.",
      icon: "electronic",
      duration: "1",
      content: { type: "exercise", seconds: 60 },
      isFree: true,
      recommendAt: 17,
    },
    {
      title: "요리 레시피 찾기",
      bundleId: 1,
      instruction: "나중에 만들어보고 싶은 새로운 요리 레시피를 찾아보세요.",
      icon: "lightbulb",
      duration: "10",
      content: { type: "search", theme: "dinner" },
      isFree: true,
      recommendAt: 18,
    },
    {
      title: "차 마시기 15분",
      bundleId: 1,
      instruction: "따뜻한 차 한 잔을 마시며 여유를 느껴보세요.",
      icon: "sound",
      duration: "15",
      content: { type: "drink", tea: "chamomile" },
      isFree: true,
      recommendAt: 21,
    },
    {
      title: "명상 가이드 듣기 30분",
      bundleId: 2,
      instruction: "전문가의 가이드에 따라 깊은 명상에 빠져보세요.",
      icon: "sound",
      duration: "30",
      content: { type: "meditation", guide: "sleep_well" },
      isFree: false,
      recommendAt: 23,
    },
    {
      title: "스트레칭 15분 (고급)",
      bundleId: 2,
      instruction: "전신을 이완시키는 고난도 스트레칭을 수행하세요.",
      icon: "vision",
      duration: "15",
      content: { type: "exercise", level: "hard" },
      isFree: false,
      recommendAt: 7,
    },
    {
      title: "영양제 챙겨먹기",
      bundleId: 1,
      instruction: "필요한 비타민이나 영양제를 잊지 말고 챙기세요.",
      icon: "lightbulb",
      duration: "1",
      content: { type: "health", item: "multivitamin" },
      isFree: true,
      recommendAt: 9,
    },
    {
      title: "외국어 한 문장 쓰기",
      bundleId: 1,
      instruction: "공부 중인 외국어로 짧은 일기를 한 문장 써보세요.",
      icon: "book",
      duration: "5",
      content: { type: "language", lang: "en" },
      isFree: true,
      recommendAt: 20,
    },
    {
      title: "뉴스 헤드라인 읽기",
      bundleId: 1,
      instruction: "오늘의 주요 뉴스 헤드라인을 빠르게 훑어보세요.",
      icon: "vision",
      duration: "5",
      content: { type: "news", source: "main" },
      isFree: true,
      recommendAt: 8,
    },
    {
      title: "손 지압하기",
      bundleId: 1,
      instruction: "피로 회복을 위해 손바닥의 혈자리를 꾹꾹 눌러주세요.",
      icon: "lightbulb",
      duration: "5",
      content: { type: "health", target: "hand" },
      isFree: true,
      recommendAt: 15,
    },
    {
      title: "내일 계획 세우기",
      bundleId: 1,
      instruction: "내일 꼭 해야 할 일 3가지를 우선순위대로 적어보세요.",
      icon: "book",
      duration: "10",
      content: { type: "plan", count: 3 },
      isFree: true,
      recommendAt: 22,
    }
  ];

  await db.insert(activityTable).values(activities);
  console.log("25개의 활동 더미 데이터가 성공적으로 생성되었습니다.");
};
